language: java
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
before_script:
  - cd netbeans-gradle-default-models
  - ./gradlew check install
  - cd ../netbeans-gradle-plugin
script: "mvn test"
branches:
  only:
    - master
