/*
 
 */
package com.jme3.gde.gui.extra.xam.model.visitor;

import com.jme3.gde.gui.extra.xam.model.AttributesType;
import com.jme3.gde.gui.extra.xam.model.ControlDefinition;
import com.jme3.gde.gui.extra.xam.model.ControlType;
import com.jme3.gde.gui.extra.xam.model.EffectValueType;
import com.jme3.gde.gui.extra.xam.model.EffectsType;
import com.jme3.gde.gui.extra.xam.model.ElementType;
import com.jme3.gde.gui.extra.xam.model.ImageType;
import com.jme3.gde.gui.extra.xam.model.InteractType;
import com.jme3.gde.gui.extra.xam.model.LayerType;
import com.jme3.gde.gui.extra.xam.model.NiftyExtensibilityElement;
import com.jme3.gde.gui.extra.xam.model.NiftyType;
import com.jme3.gde.gui.extra.xam.model.OnHoverType;
import com.jme3.gde.gui.extra.xam.model.PanelType;
import com.jme3.gde.gui.extra.xam.model.PopupType;
import com.jme3.gde.gui.extra.xam.model.RegisterEffectType;
import com.jme3.gde.gui.extra.xam.model.RegisterMouseCursorType;
import com.jme3.gde.gui.extra.xam.model.RegisterMusicType;
import com.jme3.gde.gui.extra.xam.model.RegisterSoundType;
import com.jme3.gde.gui.extra.xam.model.ResourceBundleType;
import com.jme3.gde.gui.extra.xam.model.ScreenType;
import com.jme3.gde.gui.extra.xam.model.SingleEffectType;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeBase;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeHover;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeOnHover;
import com.jme3.gde.gui.extra.xam.model.StyleType;
import com.jme3.gde.gui.extra.xam.model.TextType;
import com.jme3.gde.gui.extra.xam.model.UseControlsType;
import com.jme3.gde.gui.extra.xam.model.UseStylesType;

/**
 * Component visitor in the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface NiftyComponentVisitor {
    
    void visit(ElementType target);
    void visit(LayerType target);
    void visit(PanelType target);
    void visit(ImageType target);
    void visit(TextType target);
    void visit(ControlDefinition target);
    void visit(ControlType target);
    void visit(UseStylesType target);
    void visit(UseControlsType target);
    void visit(RegisterSoundType target);
    void visit(RegisterEffectType target);
    void visit(RegisterMusicType target);
    void visit(RegisterMouseCursorType target);
    void visit(ResourceBundleType target);
    void visit(AttributesType target);
    void visit(InteractType target);
    void visit(EffectValueType target);
    void visit(SingleEffectTypeBase target);
    void visit(SingleEffectType target);
    void visit(SingleEffectTypeOnHover target);
    void visit(OnHoverType target);
    void visit(SingleEffectTypeHover target);
    void visit(EffectsType target);
    void visit(StyleType target);
    void visit(PopupType target);
    void visit(ScreenType target);
    void visit(NiftyType target);
    void visit(NiftyExtensibilityElement target);

}