/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.AttributesType;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component attributesType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class AttributesTypeImpl extends NiftyComponentBase implements AttributesType {

    public AttributesTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public AttributesTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.ATTRIBUTESTYPE));
    }

    // attributes

    public String getHeight() {
        return getAttribute(NiftyAttribute.HEIGHT);
    }

    public void setHeight(String height) {
        setAttribute(HEIGHT_PROPERTY, NiftyAttribute.HEIGHT, height);
    }

    public String getWidth() {
        return getAttribute(NiftyAttribute.WIDTH);
    }

    public void setWidth(String width) {
        setAttribute(WIDTH_PROPERTY, NiftyAttribute.WIDTH, width);
    }

    public String getX() {
        return getAttribute(NiftyAttribute.X);
    }

    public void setX(String x) {
        setAttribute(X_PROPERTY, NiftyAttribute.X, x);
    }

    public String getY() {
        return getAttribute(NiftyAttribute.Y);
    }

    public void setY(String y) {
        setAttribute(Y_PROPERTY, NiftyAttribute.Y, y);
    }

    public String getAlign() {
        return getAttribute(NiftyAttribute.ALIGN);
    }

    public void setAlign(String align) {
        setAttribute(ALIGN_PROPERTY, NiftyAttribute.ALIGN, align);
    }

    public String getValign() {
        return getAttribute(NiftyAttribute.VALIGN);
    }

    public void setValign(String valign) {
        setAttribute(VALIGN_PROPERTY, NiftyAttribute.VALIGN, valign);
    }

    public String getPaddingLeft() {
        return getAttribute(NiftyAttribute.PADDINGLEFT);
    }

    public void setPaddingLeft(String paddingLeft) {
        setAttribute(PADDINGLEFT_PROPERTY, NiftyAttribute.PADDINGLEFT, paddingLeft);
    }

    public String getPaddingRight() {
        return getAttribute(NiftyAttribute.PADDINGRIGHT);
    }

    public void setPaddingRight(String paddingRight) {
        setAttribute(PADDINGRIGHT_PROPERTY, NiftyAttribute.PADDINGRIGHT, paddingRight);
    }

    public String getPaddingTop() {
        return getAttribute(NiftyAttribute.PADDINGTOP);
    }

    public void setPaddingTop(String paddingTop) {
        setAttribute(PADDINGTOP_PROPERTY, NiftyAttribute.PADDINGTOP, paddingTop);
    }

    public String getPaddingBottom() {
        return getAttribute(NiftyAttribute.PADDINGBOTTOM);
    }

    public void setPaddingBottom(String paddingBottom) {
        setAttribute(PADDINGBOTTOM_PROPERTY, NiftyAttribute.PADDINGBOTTOM, paddingBottom);
    }

    public String getPadding() {
        return getAttribute(NiftyAttribute.PADDING);
    }

    public void setPadding(String padding) {
        setAttribute(PADDING_PROPERTY, NiftyAttribute.PADDING, padding);
    }

    public String getChildClip() {
        return getAttribute(NiftyAttribute.CHILDCLIP);
    }

    public void setChildClip(String childClip) {
        setAttribute(CHILDCLIP_PROPERTY, NiftyAttribute.CHILDCLIP, childClip);
    }

    public String getVisible() {
        return getAttribute(NiftyAttribute.VISIBLE);
    }

    public void setVisible(String visible) {
        setAttribute(VISIBLE_PROPERTY, NiftyAttribute.VISIBLE, visible);
    }

    public String getVisibleToMouse() {
        return getAttribute(NiftyAttribute.VISIBLETOMOUSE);
    }

    public void setVisibleToMouse(String visibleToMouse) {
        setAttribute(VISIBLETOMOUSE_PROPERTY, NiftyAttribute.VISIBLETOMOUSE, visibleToMouse);
    }

    public String getChildLayout() {
        return getAttribute(NiftyAttribute.CHILDLAYOUT);
    }

    public void setChildLayout(String childLayout) {
        setAttribute(CHILDLAYOUT_PROPERTY, NiftyAttribute.CHILDLAYOUT, childLayout);
    }

    public String getFocusable() {
        return getAttribute(NiftyAttribute.FOCUSABLE);
    }

    public void setFocusable(String focusable) {
        setAttribute(FOCUSABLE_PROPERTY, NiftyAttribute.FOCUSABLE, focusable);
    }

    public String getBackgroundImage() {
        return getAttribute(NiftyAttribute.BACKGROUNDIMAGE);
    }

    public void setBackgroundImage(String backgroundImage) {
        setAttribute(BACKGROUNDIMAGE_PROPERTY, NiftyAttribute.BACKGROUNDIMAGE, backgroundImage);
    }

    public String getBackgroundColor() {
        return getAttribute(NiftyAttribute.BACKGROUNDCOLOR);
    }

    public void setBackgroundColor(String backgroundColor) {
        setAttribute(BACKGROUNDCOLOR_PROPERTY, NiftyAttribute.BACKGROUNDCOLOR, backgroundColor);
    }

    public String getColor() {
        return getAttribute(NiftyAttribute.COLOR);
    }

    public void setColor(String color) {
        setAttribute(COLOR_PROPERTY, NiftyAttribute.COLOR, color);
    }

    public String getController() {
        return getAttribute(NiftyAttribute.CONTROLLER);
    }

    public void setController(String controller) {
        setAttribute(CONTROLLER_PROPERTY, NiftyAttribute.CONTROLLER, controller);
    }

    public String getInputMapping() {
        return getAttribute(NiftyAttribute.INPUTMAPPING);
    }

    public void setInputMapping(String inputMapping) {
        setAttribute(INPUTMAPPING_PROPERTY, NiftyAttribute.INPUTMAPPING, inputMapping);
    }

    public String getTextHAlign() {
        return getAttribute(NiftyAttribute.TEXTHALIGN);
    }

    public void setTextHAlign(String textHAlign) {
        setAttribute(TEXTHALIGN_PROPERTY, NiftyAttribute.TEXTHALIGN, textHAlign);
    }

    public String getFont() {
        return getAttribute(NiftyAttribute.FONT);
    }

    public void setFont(String font) {
        setAttribute(FONT_PROPERTY, NiftyAttribute.FONT, font);
    }

    public String getFilename() {
        return getAttribute(NiftyAttribute.FILENAME);
    }

    public void setFilename(String filename) {
        setAttribute(FILENAME_PROPERTY, NiftyAttribute.FILENAME, filename);
    }

    public boolean isWrap() {
        return Boolean.parseBoolean(getAttribute(NiftyAttribute.WRAP));
    }

    public void setWrap(boolean wrap) {
        setAttribute(WRAP_PROPERTY, NiftyAttribute.WRAP, wrap);
    }

    public String getImageMode() {
        return getAttribute(NiftyAttribute.IMAGEMODE);
    }

    public void setImageMode(String imageMode) {
        setAttribute(IMAGEMODE_PROPERTY, NiftyAttribute.IMAGEMODE, imageMode);
    }

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}