/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.EffectValueType;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component effectValueType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class EffectValueTypeImpl extends NiftyComponentBase implements EffectValueType {

    public EffectValueTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public EffectValueTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.EFFECTVALUETYPE));
    }

    // attributes

    public String getTime() {
        return getAttribute(NiftyAttribute.TIME);
    }

    public void setTime(String time) {
        setAttribute(TIME_PROPERTY, NiftyAttribute.TIME, time);
    }

    public String getValue() {
        return getAttribute(NiftyAttribute.VALUE);
    }

    public void setValue(String value) {
        setAttribute(VALUE_PROPERTY, NiftyAttribute.VALUE, value);
    }

    public String getOffset() {
        return getAttribute(NiftyAttribute.OFFSET);
    }

    public void setOffset(String offset) {
        setAttribute(OFFSET_PROPERTY, NiftyAttribute.OFFSET, offset);
    }

    public String getColor() {
        return getAttribute(NiftyAttribute.COLOR);
    }

    public void setColor(String color) {
        setAttribute(COLOR_PROPERTY, NiftyAttribute.COLOR, color);
    }

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}