/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import java.util.List;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.LayerType;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.PanelType;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component layerType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class LayerTypeImpl extends NiftyComponentBase implements LayerType {

    public LayerTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public LayerTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.LAYERTYPE));
    }

    // attributes

    // child elements

    public List<PanelType> getPanelTypes() {
        return getChildren(PanelType.class);
    }

    public void addPanelType(PanelType panelType) {
        appendChild(PANELTYPE_PROPERTY, panelType);
    }

    public void removePanelType(PanelType panelType) {
        removeChild(PANELTYPE_PROPERTY, panelType);
    }

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}