/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import com.jme3.gde.gui.extra.xam.model.NiftyComponent;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import org.netbeans.modules.xml.xam.Nameable;
import org.w3c.dom.Element;

/**
 * Implementation of nameable component in the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public abstract class NameableNiftyComponentImpl extends NiftyComponentBase implements Nameable<NiftyComponent> {
    
    public NameableNiftyComponentImpl(NiftyModel model, Element e) {
        super(model, e);
    }
    
    public void setName(String name) {
        setAttribute(NAME_PROPERTY, NiftyAttribute.NAME, name);
    }

    public String getName() {
        return getAttribute(NiftyAttribute.NAME);
    }

}