/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import java.util.List;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.ElementType;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.PanelType;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component panelType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class PanelTypeImpl extends NiftyComponentBase implements PanelType {

    public PanelTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public PanelTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.PANELTYPE));
    }

    // attributes

    // child elements

    public List<ElementType> getElementTypes() {
        return getChildren(ElementType.class);
    }

    public void addElementType(ElementType elementType) {
        appendChild(ELEMENTTYPE_PROPERTY, elementType);
    }

    public void removeElementType(ElementType elementType) {
        removeChild(ELEMENTTYPE_PROPERTY, elementType);
    }

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}