/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.RegisterEffectType;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component registerEffectType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class RegisterEffectTypeImpl extends NameableNiftyComponentImpl implements RegisterEffectType {

    public RegisterEffectTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public RegisterEffectTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.REGISTEREFFECTTYPE));
    }

    // attributes

    public String getEffectClass() {
        return getAttribute(NiftyAttribute.CLASS);
    }

    public void setEffectClass(String _class) {
        setAttribute(CLASS_PROPERTY, NiftyAttribute.CLASS, _class);
    }

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}