/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeHover;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component singleEffectTypeHover.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class SingleEffectTypeHoverImpl extends NiftyComponentBase implements SingleEffectTypeHover {

    public SingleEffectTypeHoverImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public SingleEffectTypeHoverImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.SINGLEEFFECTTYPEHOVER));
    }

    // attributes

    public String getWidth() {
        return getAttribute(NiftyAttribute.WIDTH);
    }

    public void setWidth(String width) {
        setAttribute(WIDTH_PROPERTY, NiftyAttribute.WIDTH, width);
    }

    public String getHeight() {
        return getAttribute(NiftyAttribute.HEIGHT);
    }

    public void setHeight(String height) {
        setAttribute(HEIGHT_PROPERTY, NiftyAttribute.HEIGHT, height);
    }

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}