/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import java.util.List;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.OnHoverType;
import com.jme3.gde.gui.extra.xam.model.SingleEffectType;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeOnHover;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component singleEffectTypeOnHover.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class SingleEffectTypeOnHoverImpl extends SingleEffectTypeImpl implements SingleEffectTypeOnHover {

    public SingleEffectTypeOnHoverImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public SingleEffectTypeOnHoverImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.SINGLEEFFECTTYPEONHOVER));
    }

    // attributes

    // child elements

    public List<OnHoverType> getOnHoverTypes() {
        return getChildren(OnHoverType.class);
    }

    public void addOnHoverType(OnHoverType onHoverType) {
        appendChild(ONHOVERTYPE_PROPERTY, onHoverType);
    }

    public void removeOnHoverType(OnHoverType onHoverType) {
        removeChild(ONHOVERTYPE_PROPERTY, onHoverType);
    }

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}