/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.SingleEffectType;
import com.jme3.gde.gui.extra.xam.model.SingleEffectTypeBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component singleEffectType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class SingleEffectTypeImpl extends SingleEffectTypeBaseImpl implements SingleEffectType {

    public SingleEffectTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public SingleEffectTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.SINGLEEFFECTTYPE));
    }

    // attributes

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}