/*
 
 */
package com.jme3.gde.gui.extra.xam.model.impl;

import com.jme3.gde.gui.extra.xam.model.NiftyAttribute;
import org.w3c.dom.Element;
import com.jme3.gde.gui.extra.xam.model.NiftyModel;
import com.jme3.gde.gui.extra.xam.model.NiftyQName;
import com.jme3.gde.gui.extra.xam.model.UseControlsType;
import com.jme3.gde.gui.extra.xam.model.spi.NiftyComponentBase;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;	

/**
 * Implementation for domain component useControlsType.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public class UseControlsTypeImpl extends NiftyComponentBase implements UseControlsType {

    public UseControlsTypeImpl(NiftyModel model, Element element) {
        super(model, element);
    }
    
    public UseControlsTypeImpl(NiftyModel model) {
        this(model, createElementNS(model, NiftyQName.USECONTROLSTYPE));
    }

    // attributes

    public String getFilename() {
        return getAttribute(NiftyAttribute.FILENAME);
    }

    public void setFilename(String filename) {
        setAttribute(FILENAME_PROPERTY, NiftyAttribute.FILENAME, filename);
    }

    // child elements

    public void accept(NiftyComponentVisitor visitor) {
        visitor.visit(this);
    }

}