/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.gde.AnimationControlTool;

import sg.gde.AnimationControlTool.bone.BoneListPanel;
import com.jme3.animation.AnimChannel;
import com.jme3.animation.AnimControl;
import com.jme3.app.Application;
import com.jme3.app.state.AppState;
import com.jme3.app.state.AppStateManager;
import com.jme3.gde.core.scene.SceneApplication;
import com.jme3.gde.core.sceneexplorer.nodes.JmeAnimControl;
import com.jme3.gde.core.sceneexplorer.nodes.JmeSpatial;
import com.jme3.renderer.RenderManager;
import com.jme3.scene.Spatial;
import java.awt.Component;
import java.util.Collection;
import java.util.concurrent.Callable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import org.openide.util.LookupEvent;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupListener;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.MyTool.AnimationControlTool//AniControl_//EN",
autostore = false)
@TopComponent.Description(preferredID = "AniControl_TopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "org.MyTool.AnimationControlTool.AniControl_TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_AniControl_Action",
preferredID = "AniControl_TopComponent")
public final class AniControl_TopComponent extends TopComponent implements LookupListener, AppState {

    private DefaultComboBoxModel comboModel;
    private BoneListPanel boneListPanel;

    public AniControl_TopComponent() {
        initComponents();
        setName(NbBundle.getMessage(AniControl_TopComponent.class, "CTL_AniControl_TopComponent"));
        setToolTipText(NbBundle.getMessage(AniControl_TopComponent.class, "HINT_AniControl_TopComponent"));
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        //initTestPanel();
        boneListPanel.initBonePanel();
        //enableLogger();
    }

    void enableLogger() {
        //Logger.getLogger("").setLevel(Level.FINE);
        //Logger.getLogger("").info("Hehe is good");
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAnimation = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblTimePos = new javax.swing.JLabel();
        sliderAnimPos = new javax.swing.JSlider();
        jComboBox1 = new javax.swing.JComboBox();
        lblMaxTime = new javax.swing.JLabel();
        btnForward = new javax.swing.JButton();
        btnBackward = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        sliderAnimSpeed = new javax.swing.JSlider();
        lblSpeedValue = new javax.swing.JLabel();
        btnSpeedDown = new javax.swing.JButton();
        btnSpeedUp = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 80));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(lblTimePos, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.lblTimePos.text")); // NOI18N

        sliderAnimPos.setMinorTickSpacing(10);
        sliderAnimPos.setPaintLabels(true);
        sliderAnimPos.setPaintTicks(true);
        sliderAnimPos.setToolTipText(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.sliderAnimPos.toolTipText")); // NOI18N
        sliderAnimPos.setValue(0);
        sliderAnimPos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAnimPosStateChanged(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(lblMaxTime, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.lblMaxTime.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnForward, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnForward.text")); // NOI18N
        btnForward.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnForward.setBorderPainted(false);

        org.openide.awt.Mnemonics.setLocalizedText(btnBackward, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnBackward.text")); // NOI18N
        btnBackward.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBackward.setBorderPainted(false);
        btnBackward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackwardMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnPlayPause, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnPlayPause.text")); // NOI18N
        btnPlayPause.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPlayPause.setBorderPainted(false);
        btnPlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayPauseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnForward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sliderAnimPos, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblTimePos)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaxTime))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnForward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(sliderAnimPos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxTime)
                    .addComponent(lblTimePos)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.jPanel8.border.title"))); // NOI18N

        sliderAnimSpeed.setMaximum(20);
        sliderAnimSpeed.setMinimum(-20);
        sliderAnimSpeed.setValue(0);
        sliderAnimSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAnimSpeedStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblSpeedValue, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.lblSpeedValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnSpeedDown, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnSpeedDown.text")); // NOI18N
        btnSpeedDown.setActionCommand(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnSpeedDown.actionCommand")); // NOI18N
        btnSpeedDown.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSpeedDown.setBorderPainted(false);
        btnSpeedDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSpeedDownMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnSpeedUp, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnSpeedUp.text")); // NOI18N
        btnSpeedUp.setActionCommand(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.btnSpeedUp.actionCommand")); // NOI18N
        btnSpeedUp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSpeedUp.setBorderPainted(false);
        btnSpeedUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSpeedUpMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.jCheckBox1.text")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnSpeedDown, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderAnimSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpeedUp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSpeedValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSpeedUp)
                        .addComponent(lblSpeedValue)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSpeedDown)
                    .addComponent(sliderAnimSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAnimationLayout = new javax.swing.GroupLayout(panelAnimation);
        panelAnimation.setLayout(panelAnimationLayout);
        panelAnimationLayout.setHorizontalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelAnimationLayout.setVerticalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimationLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.panelAnimation.TabConstraints.tabTitle"), panelAnimation); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(AniControl_TopComponent.class, "AniControl_TopComponent.jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpeedUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpeedUpMouseClicked
        // TODO add your handling code here:
        SceneApplication.getApplication().enqueue(new Callable() {

            public Object call() throws Exception {
                if (playState != 0) {
                    if (channel.getSpeed() < 10) {
                        channel.setSpeed(channel.getSpeed() * 2);
                        currentSpeed = channel.getSpeed();
                    } else {
                        currentSpeed = channel.getSpeed();
                    }
                }
                return null;
            }
        });
        updateSliderState();
    }//GEN-LAST:event_btnSpeedUpMouseClicked

    private void btnSpeedDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpeedDownMouseClicked
        // TODO add your handling code here:
        SceneApplication.getApplication().enqueue(new Callable() {

            public Object call() throws Exception {
                if (playState != 0) {
                    if (channel.getSpeed() > 0.1f) {
                        channel.setSpeed(channel.getSpeed() / 2);
                        currentSpeed = channel.getSpeed();
                    } else {
                        currentSpeed = channel.getSpeed();
                    }
                }
                return null;
            }
        });
        updateSliderState();
    }//GEN-LAST:event_btnSpeedDownMouseClicked

    private void sliderAnimSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAnimSpeedStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderAnimSpeedStateChanged

    private void btnPlayPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayPauseMouseClicked
        // TODO add your handling code here:
        SceneApplication.getApplication().enqueue(new Callable() {

            public Object call() throws Exception {
                if (playState == 0) {
                    //currentTime = channel.getTime();
                    currentSpeed = channel.getSpeed();
                    //channel.setTime(currentTime);
                    channel.setSpeed(0);
                    playState = 1;
                } else {
                    channel.setSpeed(currentSpeed);
                    playState = 0;
                }
                return null;
            }
        });
    }//GEN-LAST:event_btnPlayPauseMouseClicked

    private void btnBackwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackwardMouseClicked
        // TODO add your handling code here:
        SceneApplication.getApplication().enqueue(new Callable() {

            public Object call() throws Exception {
                float spf = (float) 1 / 24;
                currentTime = channel.getTime();
                float maxTime = channel.getAnimMaxTime();
                if (currentTime - spf >= 0) {
                    currentTime = currentTime - spf;
                } else {
                    currentTime = maxTime;
                }
                System.out.println("Time : " + currentTime + "  _ " + spf);
                channel.setTime(currentTime);
                channel.setSpeed(0);

                playState = 1;
                return null;
            }
        });
    }//GEN-LAST:event_btnBackwardMouseClicked

    private void sliderAnimPosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAnimPosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderAnimPosStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnSpeedDown;
    private javax.swing.JButton btnSpeedUp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMaxTime;
    private javax.swing.JLabel lblSpeedValue;
    private javax.swing.JLabel lblTimePos;
    private javax.swing.JPanel panelAnimation;
    private javax.swing.JSlider sliderAnimPos;
    private javax.swing.JSlider sliderAnimSpeed;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        registerListener();
        setActive(false);
        disableAll();
        clearAllData();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        endJob();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    private Result<JmeAnimControl> result;

//method to register the listener;
    private void registerListener() {
        TopComponent tc = WindowManager.getDefault().findTopComponent("SceneExplorerTopComponent");

        Lookup tcLookup = tc.getLookup();
        result = tcLookup.lookupResult(JmeAnimControl.class);
        result.addLookupListener(this);
    }
    
    public AnimChannel channel;
    public AnimControl animControl;
    private String currentAnimName = "";
    private float currentTime = 0;
    private float currentSpeed = 1;
    private int playState = 0;
    private float maxTime;
    Spatial realSpatial;
    boolean isActiveNow;
    DefaultListModel listModel;
//implements org.openide.util.LookupListener (called from AWT thread)

    @Override
    public void resultChanged(LookupEvent ev) {
        Collection<JmeAnimControl> items = (Collection<JmeAnimControl>) result.allInstances();
        for (JmeAnimControl node1 : items) {

            JmeSpatial parentNode = (JmeSpatial) node1.getParentNode();
            String des1 = parentNode.getDisplayName();
            animControl = node1.getLookup().lookup(AnimControl.class);
            realSpatial = parentNode.getLookup().lookup(Spatial.class);
            updateChannels();
            updateAnimList();
            boneListPanel.updateBoneTable();
            updateTimeValue();
            updateSliderState();
            boneListPanel.initBonePanel();
            if (!SceneApplication.getApplication().getStateManager().hasState(this)) {
                SceneApplication.getApplication().getStateManager().attach(this);
            }
            setActive(true);
            enableAll();
            return;
        }

        if (items.isEmpty()) {
            endJob();
        }

    }

    void endJob() {
        if (SceneApplication.getApplication().getStateManager().hasState(this)) {
            SceneApplication.getApplication().getStateManager().detach(this);
        }
        //lblName.setText("Out ->");
        clearAllData();
        disableAll();
    }

    void updateAnimList() {
        listModel = new DefaultListModel();
        comboModel = new DefaultComboBoxModel();

        for (String name : animControl.getAnimationNames()) {
            listModel.addElement(name);
            comboModel.addElement(name);
        }
        //animList.setModel(listModel);
        //comboAnimList.setModel(comboModel);

        //animList.setSelectedValue(currentAnimName, true);
        //comboAnimList.setSelectedItem(currentAnimName);
    }

    void updateChannels() {
        if (animControl.getNumChannels() > 0) {
            channel = animControl.getChannel(0);
            //lblName.setText("getChannel");
        } else {
            channel = animControl.createChannel();
            //lblName.setText("CreateChanel");
        }
    }

    void updateSliderState() {
        int max = sliderAnimPos.getMaximum();
        int min = sliderAnimPos.getMinimum();
        sliderAnimPos.setValue(min + Math.round(currentTime * max / maxTime));

        sliderAnimSpeed.setValue(Math.round(currentSpeed));
        lblSpeedValue.setText(currentSpeed + "X");
    }

    void updateTimeValue() {
        currentTime = channel.getTime();
        maxTime = channel.getAnimMaxTime();
        lblMaxTime.setText(new Float(maxTime).toString());
        lblTimePos.setText(new Float(currentTime).toString());
    }

    void clearAllData() {
        if (listModel != null) {

            listModel.clear();
        } else {
            //animList.setListData(new String[]{});
        }
        if (comboModel != null) {
            comboModel.removeAllElements();
        } else {
            //comboAnimList.removeAllItems();
        }
        sliderAnimPos.setValue(0);
        sliderAnimSpeed.setValue(1);
        lblSpeedValue.setText("1X");
        lblMaxTime.setText("00:00");
        lblTimePos.setText("00:00");

    }

    @Override
    public void update(float f) {

        if (isActive()) {
            if (animControl.getNumChannels() > 0 && animControl.getChannel(0) != null && channel != animControl.getChannel(0)) {
                updateChannels();
            }

            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    String currentAnimName = channel.getAnimationName();
                    if ((currentAnimName != null) && (!currentAnimName.equals("null"))) {
                        updateTimeValue();
                        updateSliderState();
                    }
                }
            });


            //lblName.setText(currentAnimName + count + "is Active & Update");
            count++;
        }


        //Logger.getLogger(AniControl_TopComponent.class.getName()).warning("update!");

    }
    private int count = 0;

    @Override
    public void initialize(AppStateManager asm, Application aplctn) {
        isActiveNow = false;
    }

    @Override
    public boolean isInitialized() {
        return true;
    }

    public void setActive(boolean bln) {
        isActiveNow = bln;
    }

    public boolean isActive() {
        return isActiveNow;
    }

    @Override
    public void stateAttached(AppStateManager asm) {
    }

    @Override
    public void stateDetached(AppStateManager asm) {
    }

    @Override
    public void render(RenderManager rm) {
    }

    @Override
    public void postRender() {
    }

    @Override
    public void cleanup() {
    }

    private void disableAll() {
        //jTabbedPane1.setEnabled(false);
        disablePanel(panelAnimation);
    }

    void disablePanel(JPanel panel) {
        for (Component component : panel.getComponents()) {
            component.setEnabled(false);
            component.setFocusable(false);
            if (component instanceof JPanel) {
                disablePanel((JPanel) component);
            }
        }
        return;
    }

    void enablePanel(JPanel panel) {
        for (Component component : panel.getComponents()) {
            component.setEnabled(true);
            component.setFocusable(true);
            if (component instanceof JPanel) {
                enablePanel((JPanel) component);
            }
        }
    }

    private void enableAll() {
        //jTabbedPane1.setEnabled(true);
        enablePanel(panelAnimation);
    }
}
