/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component attributesType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface AttributesType extends NiftyComponent {

    // attribute property change event names
    public static final String HEIGHT_PROPERTY = "height"; // NOI18N
    public static final String WIDTH_PROPERTY = "width"; // NOI18N
    public static final String X_PROPERTY = "x"; // NOI18N
    public static final String Y_PROPERTY = "y"; // NOI18N
    public static final String ALIGN_PROPERTY = "align"; // NOI18N
    public static final String VALIGN_PROPERTY = "valign"; // NOI18N
    public static final String PADDINGLEFT_PROPERTY = "paddingLeft"; // NOI18N
    public static final String PADDINGRIGHT_PROPERTY = "paddingRight"; // NOI18N
    public static final String PADDINGTOP_PROPERTY = "paddingTop"; // NOI18N
    public static final String PADDINGBOTTOM_PROPERTY = "paddingBottom"; // NOI18N
    public static final String PADDING_PROPERTY = "padding"; // NOI18N
    public static final String CHILDCLIP_PROPERTY = "childClip"; // NOI18N
    public static final String VISIBLE_PROPERTY = "visible"; // NOI18N
    public static final String VISIBLETOMOUSE_PROPERTY = "visibleToMouse"; // NOI18N
    public static final String CHILDLAYOUT_PROPERTY = "childLayout"; // NOI18N
    public static final String FOCUSABLE_PROPERTY = "focusable"; // NOI18N
    public static final String BACKGROUNDIMAGE_PROPERTY = "backgroundImage"; // NOI18N
    public static final String BACKGROUNDCOLOR_PROPERTY = "backgroundColor"; // NOI18N
    public static final String COLOR_PROPERTY = "color"; // NOI18N
    public static final String CONTROLLER_PROPERTY = "controller"; // NOI18N
    public static final String INPUTMAPPING_PROPERTY = "inputMapping"; // NOI18N
    public static final String TEXTHALIGN_PROPERTY = "textHAlign"; // NOI18N
    public static final String FONT_PROPERTY = "font"; // NOI18N
    public static final String FILENAME_PROPERTY = "filename"; // NOI18N
    public static final String WRAP_PROPERTY = "wrap"; // NOI18N
    public static final String IMAGEMODE_PROPERTY = "imageMode"; // NOI18N
    // child element property change event names

    public String getHeight();
    public void setHeight(String height);
	
    public String getWidth();
    public void setWidth(String width);
	
    public String getX();
    public void setX(String x);
	
    public String getY();
    public void setY(String y);
	
    public String getAlign();
    public void setAlign(String align);
	
    public String getValign();
    public void setValign(String valign);
	
    public String getPaddingLeft();
    public void setPaddingLeft(String paddingLeft);
	
    public String getPaddingRight();
    public void setPaddingRight(String paddingRight);
	
    public String getPaddingTop();
    public void setPaddingTop(String paddingTop);
	
    public String getPaddingBottom();
    public void setPaddingBottom(String paddingBottom);
	
    public String getPadding();
    public void setPadding(String padding);
	
    public String getChildClip();
    public void setChildClip(String childClip);
	
    public String getVisible();
    public void setVisible(String visible);
	
    public String getVisibleToMouse();
    public void setVisibleToMouse(String visibleToMouse);
	
    public String getChildLayout();
    public void setChildLayout(String childLayout);
	
    public String getFocusable();
    public void setFocusable(String focusable);
	
    public String getBackgroundImage();
    public void setBackgroundImage(String backgroundImage);
	
    public String getBackgroundColor();
    public void setBackgroundColor(String backgroundColor);
	
    public String getColor();
    public void setColor(String color);
	
    public String getController();
    public void setController(String controller);
	
    public String getInputMapping();
    public void setInputMapping(String inputMapping);
	
    public String getTextHAlign();
    public void setTextHAlign(String textHAlign);
	
    public String getFont();
    public void setFont(String font);
	
    public String getFilename();
    public void setFilename(String filename);
	
    public boolean isWrap();
    public void setWrap(boolean wrap);
	
    public String getImageMode();
    public void setImageMode(String imageMode);
	
}