/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import org.netbeans.modules.xml.xam.Nameable;

/**
 * Interface for domain component controlType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface ControlType extends NiftyComponent, ElementType, Nameable<NiftyComponent> {

    // attribute property change event names
    public static final String ONCHANGE_PROPERTY = "onChange"; // NOI18N
    // child element property change event names

    public String getOnChange();
    public void setOnChange(String onChange);
	
}