/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

/**
 * An enum type in the Nifty domain.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public enum DirectionType {
    TOP("top"),   // NOI18N
    BOTTOM("bottom"),   // NOI18N
    LEFT("left"),   // NOI18N
    RIGHT("right"),   // NOI18N
    ;

    private DirectionType(String value) {
        this.value = value;
    }
    
    public String getValue() {
        return value;
    }
    
    public static DirectionType getDirectionType(String value) {
        if (value == null) {
            return null;
        } else if ("top".equals(value)) {   // NOI18N
            return TOP;
        } else if ("bottom".equals(value)) {   // NOI18N
            return BOTTOM;
        } else if ("left".equals(value)) {   // NOI18N
            return LEFT;
        } else if ("right".equals(value)) {   // NOI18N
            return RIGHT;
        } else {
            assert false : "Invalid choice: " + value; 
            return null;
        }
    }
    
    private final String value;
}
