/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component effectsType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface EffectsType extends NiftyComponent {

    // attribute property change event names
    public static final String OVERLAY_PROPERTY = "overlay"; // NOI18N
    // child element property change event names
    public static final String SINGLEEFFECTTYPE_PROPERTY = "singleEffectType"; // NOI18N

    public boolean isOverlay();
    public void setOverlay(boolean overlay);
	
    public List<SingleEffectType> getSingleEffectTypes();
    public void addSingleEffectType(SingleEffectType singleEffectType);
    public void removeSingleEffectType(SingleEffectType singleEffectType);

}