/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component elementType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface ElementType extends NiftyComponent {

    // attribute property change event names
    public static final String ID_PROPERTY = "id"; // NOI18N
    public static final String WIDTH_PROPERTY = "width"; // NOI18N
    public static final String HEIGHT_PROPERTY = "height"; // NOI18N
    public static final String ALIGN_PROPERTY = "align"; // NOI18N
    public static final String VALIGN_PROPERTY = "valign"; // NOI18N
    public static final String CHILDLAYOUT_PROPERTY = "childLayout"; // NOI18N
    public static final String CHILDCLIP_PROPERTY = "childClip"; // NOI18N
    public static final String BACKGROUNDIMAGE_PROPERTY = "backgroundImage"; // NOI18N
    public static final String BACKGROUNDCOLOR_PROPERTY = "backgroundColor"; // NOI18N
    public static final String VISIBLETOMOUSE_PROPERTY = "visibleToMouse"; // NOI18N
    public static final String STYLE_PROPERTY = "style"; // NOI18N
    // child element property change event names
    public static final String INTERACTTYPE_PROPERTY = "interactType"; // NOI18N
    public static final String EFFECTSTYPE_PROPERTY = "effectsType"; // NOI18N

    public String getId();
    public void setId(String id);
	
    public String getWidth();
    public void setWidth(String width);
	
    public String getHeight();
    public void setHeight(String height);
	
    public AlignType getAlign();
    public void setAlign(AlignType align);
	
    public ValignType getValign();
    public void setValign(ValignType valign);
	
    public LayoutType getChildLayout();
    public void setChildLayout(LayoutType childLayout);
	
    public boolean isChildClip();
    public void setChildClip(boolean childClip);
	
    public String getBackgroundImage();
    public void setBackgroundImage(String backgroundImage);
	
    public String getBackgroundColor();
    public void setBackgroundColor(String backgroundColor);
	
    public boolean isVisibleToMouse();
    public void setVisibleToMouse(boolean visibleToMouse);
	
    public String getStyle();
    public void setStyle(String style);
	
    public List<InteractType> getInteractTypes();
    public void addInteractType(InteractType interactType);
    public void removeInteractType(InteractType interactType);

    public List<EffectsType> getEffectsTypes();
    public void addEffectsType(EffectsType effectsType);
    public void removeEffectsType(EffectsType effectsType);

}