/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component imageType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface ImageType extends NiftyComponent, ElementType {

    // attribute property change event names
    public static final String FILENAME_PROPERTY = "filename"; // NOI18N
    public static final String X_PROPERTY = "x"; // NOI18N
    public static final String Y_PROPERTY = "y"; // NOI18N
    public static final String FILTER_PROPERTY = "filter"; // NOI18N
    public static final String IMAGEMODE_PROPERTY = "imageMode"; // NOI18N
    public static final String SUBIMAGESIZEMODE_PROPERTY = "subImageSizeMode"; // NOI18N
    public static final String RESIZEHINT_PROPERTY = "resizeHint"; // NOI18N
    // child element property change event names

    public String getFilename();
    public void setFilename(String filename);
	
    public String getX();
    public void setX(String x);
	
    public String getY();
    public void setY(String y);
	
    public boolean isFilter();
    public void setFilter(boolean filter);
	
    public String getImageMode();
    public void setImageMode(String imageMode);
	
    public SubImageSizeModeType getSubImageSizeMode();
    public void setSubImageSizeMode(SubImageSizeModeType subImageSizeMode);
	
    public String getResizeHint();
    public void setResizeHint(String resizeHint);
	
}