/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component interactType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface InteractType extends NiftyComponent {

    // attribute property change event names
    public static final String ONCLICK_PROPERTY = "onClick"; // NOI18N
    public static final String ONRELEASE_PROPERTY = "onRelease"; // NOI18N
    public static final String ONMOUSEOVER_PROPERTY = "onMouseOver"; // NOI18N
    public static final String ONCLICKREPEAT_PROPERTY = "onClickRepeat"; // NOI18N
    public static final String ONCLICKMOUSEMOVE_PROPERTY = "onClickMouseMove"; // NOI18N
    public static final String ONCLICKALTERNATEKEY_PROPERTY = "onClickAlternateKey"; // NOI18N
    // child element property change event names

    public String getOnClick();
    public void setOnClick(String onClick);
	
    public String getOnRelease();
    public void setOnRelease(String onRelease);
	
    public String getOnMouseOver();
    public void setOnMouseOver(String onMouseOver);
	
    public String getOnClickRepeat();
    public void setOnClickRepeat(String onClickRepeat);
	
    public String getOnClickMouseMove();
    public void setOnClickMouseMove(String onClickMouseMove);
	
    public String getOnClickAlternateKey();
    public void setOnClickAlternateKey(String onClickAlternateKey);
	
}