/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component layerType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface LayerType extends NiftyComponent {

    // attribute property change event names
    // child element property change event names
    public static final String PANELTYPE_PROPERTY = "panelType"; // NOI18N

    public List<PanelType> getPanelTypes();
    public void addPanelType(PanelType panelType);
    public void removePanelType(PanelType panelType);

}