/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

/**
 * An enum type in the Nifty domain.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public enum LayoutType {
    VERTICAL("vertical"),   // NOI18N
    CENTER("center"),   // NOI18N
    ABSOLUTE("absolute"),   // NOI18N
    HORIZONTAL("horizontal"),   // NOI18N
    OVERLAY("overlay"),   // NOI18N
    ;

    private LayoutType(String value) {
        this.value = value;
    }
    
    public String getValue() {
        return value;
    }
    
    public static LayoutType getLayoutType(String value) {
        if (value == null) {
            return null;
        } else if ("vertical".equals(value)) {   // NOI18N
            return VERTICAL;
        } else if ("center".equals(value)) {   // NOI18N
            return CENTER;
        } else if ("absolute".equals(value)) {   // NOI18N
            return ABSOLUTE;
        } else if ("horizontal".equals(value)) {   // NOI18N
            return HORIZONTAL;
        } else if ("overlay".equals(value)) {   // NOI18N
            return OVERLAY;
        } else {
            assert false : "Invalid choice: " + value; 
            return null;
        }
    }
    
    private final String value;
}
