/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.HashSet;
import java.util.Set;
import javax.xml.namespace.QName;

/**
 * QNames for all the elements in the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public enum NiftyQName {    
    
    ELEMENTTYPE(createQName("elementType")), // NOI18N
    LAYERTYPE(createQName("layerType")), // NOI18N
    PANELTYPE(createQName("panelType")), // NOI18N
    IMAGETYPE(createQName("imageType")), // NOI18N
    TEXTTYPE(createQName("textType")), // NOI18N
    CONTROLDEFINITION(createQName("controlDefinition")), // NOI18N
    CONTROLTYPE(createQName("controlType")), // NOI18N
    USESTYLESTYPE(createQName("useStylesType")), // NOI18N
    USECONTROLSTYPE(createQName("useControlsType")), // NOI18N
    REGISTERSOUNDTYPE(createQName("registerSoundType")), // NOI18N
    REGISTEREFFECTTYPE(createQName("registerEffectType")), // NOI18N
    REGISTERMUSICTYPE(createQName("registerMusicType")), // NOI18N
    REGISTERMOUSECURSORTYPE(createQName("registerMouseCursorType")), // NOI18N
    RESOURCEBUNDLETYPE(createQName("resourceBundleType")), // NOI18N
    ATTRIBUTESTYPE(createQName("attributesType")), // NOI18N
    INTERACTTYPE(createQName("interactType")), // NOI18N
    EFFECTVALUETYPE(createQName("effectValueType")), // NOI18N
    SINGLEEFFECTTYPEBASE(createQName("singleEffectTypeBase")), // NOI18N
    SINGLEEFFECTTYPE(createQName("singleEffectType")), // NOI18N
    SINGLEEFFECTTYPEONHOVER(createQName("singleEffectTypeOnHover")), // NOI18N
    ONHOVERTYPE(createQName("onHoverType")), // NOI18N
    SINGLEEFFECTTYPEHOVER(createQName("singleEffectTypeHover")), // NOI18N
    EFFECTSTYPE(createQName("effectsType")), // NOI18N
    STYLETYPE(createQName("styleType")), // NOI18N
    POPUPTYPE(createQName("popupType")), // NOI18N
    SCREENTYPE(createQName("screenType")), // NOI18N
    NIFTYTYPE(createQName("niftyType")), // NOI18N
    ;
    
    public static final String NS_URI = "http://nifty-gui.sourceforge.net/nifty-1.3.xsd";  // NOI18N
    public static final String NS_PREFIX = "nifty";   // NOI18N        
    
    public static QName createQName(String localName){
        return new QName(NS_URI, localName, NS_PREFIX);
    }
    
    private NiftyQName(QName name) {
        qName = name;
    }
    
    public QName getQName(){
        return qName;
    }
    
    private static Set<QName> qnames = null;
    public static Set<QName> getQNames() {
        if (qnames == null) {
            qnames = new HashSet<QName>();
            for (NiftyQName wq : values()) {
                qnames.add(wq.getQName());
            }
        }
        return qnames;
    }    
    
    public String getQualifiedName() {
        return qName.getPrefix() + ":" + qName.getLocalPart();      // NOI18N
    }
    
    private final QName qName;
}
