/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import org.netbeans.modules.xml.xam.ModelSource;
import org.netbeans.modules.xml.xam.dom.AbstractDocumentModel;

/**
 * Model for the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public abstract class NiftyModel extends AbstractDocumentModel<NiftyComponent> { 
    
    protected NiftyModel(ModelSource source) {
        super(source);
    }
    
    public abstract NiftyComponentFactory getFactory();

    /**
     * Gets domain-specific root component.
     */
    public abstract NiftyType getNiftyType();

}
