/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;
import javax.xml.namespace.QName;
import com.jme3.gde.gui.extra.xam.model.visitor.NiftyComponentVisitor;
import org.netbeans.modules.xml.xam.dom.DocumentComponent;
import org.netbeans.modules.xml.xam.dom.NamedComponentReference;

/**
 * Interface for all the components in the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface NiftyComponent extends DocumentComponent<NiftyComponent> {
    
    public static final String EXTENSIBILITY_ELEMENT_PROPERTY = "extensibilityElement"; // NOI18N
    
    /**
     * Get the owner model of this component.
     * 
     * @return  the owner model
     */
    NiftyModel getModel();
    
    void accept(NiftyComponentVisitor visitor);
        
    /**
     * Creates a global reference to the given target component.
     * 
     * @param target    the target component
     * @param type      actual type of the target
     * 
     * @return the global reference.
     */
    <T extends ReferenceableNiftyComponent> NamedComponentReference<T> 
            createReferenceTo(T target, Class<T> type);

    /**
     * Adds a child extensibility element.
     * 
     * @param ee    a new child extensibility element
     */
    void addExtensibilityElement(NiftyExtensibilityElement ee);
    
    /**
     * Removes an existing child extensibility element.
     * 
     * @param ee    an existing child extensibility element
     */
    void removeExtensibilityElement(NiftyExtensibilityElement ee);
    
    /**
     * Gets a list of all child extensibility elements.
     * 
     * @return  a list of all child extensibility elements
     */
    List<NiftyExtensibilityElement> getExtensibilityElements();
    
    /**
     * Gets a list of child extensibility elements of the given type.
     * 
     * @param type  type of child extensibility elements
     * @return  a list of child extensibility elements of the given type
     */
    <T extends NiftyExtensibilityElement> List<T> getExtensibilityElements(Class<T> type);
        
    /**
     * Gets the value of an attribute in any namespace.
     * 
     * @param qname attribute QName 
     * 
     * @return  attribute value
     */
    String getAnyAttribute(QName qname);
    
    /**
     * Sets the value of an attribute in any namespace.
     * 
     * @param qname attribute QName 
     * @param value new attribute value
     */
    void setAnyAttribute(QName qname, String value);
}
