/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import javax.xml.namespace.QName;
import org.netbeans.modules.xml.xam.dom.Attribute;

/**
 * Attributes in the Nifty domain.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public enum NiftyAttribute implements Attribute {
        NS("xmlns"),            // NOI18N 
        ALIGN("align"), // NOI18N
        ALTERNATEDISABLE("alternateDisable"), // NOI18N
        ALTERNATEENABLE("alternateEnable"), // NOI18N
        BACKGROUNDCOLOR("backgroundColor"), // NOI18N
        BACKGROUNDIMAGE("backgroundImage"), // NOI18N
        BASE("base"), // NOI18N
        CHILDCLIP("childClip"), // NOI18N
        CHILDLAYOUT("childLayout"), // NOI18N
        CLASS("class"), // NOI18N
        COLOR("color"), // NOI18N
        CONTROLLER("controller"), // NOI18N
        DEFAULTFOCUSELEMENT("defaultFocusElement"), // NOI18N
        FACTOR("factor"), // NOI18N
        FILENAME("filename"), // NOI18N
        FILTER("filter"), // NOI18N
        FOCUSABLE("focusable"), // NOI18N
        FONT("font"), // NOI18N
        HEIGHT("height"), // NOI18N
        HOTSPOTX("hotspotX"), // NOI18N
        HOTSPOTY("hotspotY"), // NOI18N
        HOVERFALLOFFCONSTRAINT("hoverFalloffConstraint"), // NOI18N
        HOVERFALLOFFTYPE("hoverFalloffType"), // NOI18N
        HOVERHEIGHT("hoverHeight"), // NOI18N
        HOVERWIDTH("hoverWidth"), // NOI18N
        ID("id"), // NOI18N
        IMAGEMODE("imageMode"), // NOI18N
        INHERIT("inherit"), // NOI18N
        INPUTMAPPING("inputMapping"), // NOI18N
        LAYOUT("layout"), // NOI18N
        LENGTH("length"), // NOI18N
        NAME("name"), // NOI18N
        OFFSET("offset"), // NOI18N
        ONCHANGE("onChange"), // NOI18N
        ONCLICK("onClick"), // NOI18N
        ONCLICKALTERNATEKEY("onClickAlternateKey"), // NOI18N
        ONCLICKMOUSEMOVE("onClickMouseMove"), // NOI18N
        ONCLICKREPEAT("onClickRepeat"), // NOI18N
        ONENDEFFECT("onEndEffect"), // NOI18N
        ONMOUSEOVER("onMouseOver"), // NOI18N
        ONRELEASE("onRelease"), // NOI18N
        ONSTARTEFFECT("onStartEffect"), // NOI18N
        ONESHOT("oneShot"), // NOI18N
        OVERLAY("overlay"), // NOI18N
        PADDING("padding"), // NOI18N
        PADDINGBOTTOM("paddingBottom"), // NOI18N
        PADDINGLEFT("paddingLeft"), // NOI18N
        PADDINGRIGHT("paddingRight"), // NOI18N
        PADDINGTOP("paddingTop"), // NOI18N
        POST("post"), // NOI18N
        RESIZEHINT("resizeHint"), // NOI18N
        STARTDELAY("startDelay"), // NOI18N
        STYLE("style"), // NOI18N
        SUBIMAGESIZEMODE("subImageSizeMode"), // NOI18N
        TEXT("text"), // NOI18N
        TEXTHALIGN("textHAlign"), // NOI18N
        TIME("time"), // NOI18N
        TIMETYPE("timeType"), // NOI18N
        VALIGN("valign"), // NOI18N
        VALUE("value"), // NOI18N
        VISIBLE("visible"), // NOI18N
        VISIBLETOMOUSE("visibleToMouse"), // NOI18N
        WIDTH("width"), // NOI18N
        WRAP("wrap"), // NOI18N
        X("x"), // NOI18N
        Y("y"), // NOI18N
        ;
    
    private String name;
    private Class type;
    private Class subtype;
    
    /**
     * Creates a new instance of NiftyAttribute
     */
    NiftyAttribute(String name) {
        this(name, String.class);
    }
    
    NiftyAttribute(String name, Class type) {
        this(name, type, null);
    }
    
    NiftyAttribute(String name, Class type, Class subtype) {
        this.name = name;
        this.type = type;
        this.subtype = subtype;
    }
    
    @Override
    public String toString() { 
        return name; 
    }

    public Class getType() {
        return type;
    }

    public String getName() { 
        return name; 
    }

    public Class getMemberType() { 
        return subtype; 
    }

    public QName getQName() {
        return new QName(name);
    }
}