/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component niftyType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface NiftyType extends NiftyComponent {

    // attribute property change event names
    // child element property change event names
    public static final String USESTYLESTYPE_PROPERTY = "useStylesType"; // NOI18N
    public static final String USECONTROLSTYPE_PROPERTY = "useControlsType"; // NOI18N
    public static final String REGISTERSOUNDTYPE_PROPERTY = "registerSoundType"; // NOI18N
    public static final String REGISTEREFFECTTYPE_PROPERTY = "registerEffectType"; // NOI18N
    public static final String REGISTERMUSICTYPE_PROPERTY = "registerMusicType"; // NOI18N
    public static final String REGISTERMOUSECURSORTYPE_PROPERTY = "registerMouseCursorType"; // NOI18N
    public static final String RESOURCEBUNDLETYPE_PROPERTY = "resourceBundleType"; // NOI18N
    public static final String STYLETYPE_PROPERTY = "styleType"; // NOI18N
    public static final String CONTROLDEFINITION_PROPERTY = "controlDefinition"; // NOI18N
    public static final String SCREENTYPE_PROPERTY = "screenType"; // NOI18N

    public List<UseStylesType> getUseStylesTypes();
    public void addUseStylesType(UseStylesType useStylesType);
    public void removeUseStylesType(UseStylesType useStylesType);

    public List<UseControlsType> getUseControlsTypes();
    public void addUseControlsType(UseControlsType useControlsType);
    public void removeUseControlsType(UseControlsType useControlsType);

    public List<RegisterSoundType> getRegisterSoundTypes();
    public void addRegisterSoundType(RegisterSoundType registerSoundType);
    public void removeRegisterSoundType(RegisterSoundType registerSoundType);

    public List<RegisterEffectType> getRegisterEffectTypes();
    public void addRegisterEffectType(RegisterEffectType registerEffectType);
    public void removeRegisterEffectType(RegisterEffectType registerEffectType);

    public List<RegisterMusicType> getRegisterMusicTypes();
    public void addRegisterMusicType(RegisterMusicType registerMusicType);
    public void removeRegisterMusicType(RegisterMusicType registerMusicType);

    public List<RegisterMouseCursorType> getRegisterMouseCursorTypes();
    public void addRegisterMouseCursorType(RegisterMouseCursorType registerMouseCursorType);
    public void removeRegisterMouseCursorType(RegisterMouseCursorType registerMouseCursorType);

    public List<ResourceBundleType> getResourceBundleTypes();
    public void addResourceBundleType(ResourceBundleType resourceBundleType);
    public void removeResourceBundleType(ResourceBundleType resourceBundleType);

    public List<StyleType> getStyleTypes();
    public void addStyleType(StyleType styleType);
    public void removeStyleType(StyleType styleType);

    public List<ControlDefinition> getControlDefinitions();
    public void addControlDefinition(ControlDefinition controlDefinition);
    public void removeControlDefinition(ControlDefinition controlDefinition);

    public List<ScreenType> getScreenTypes();
    public void addScreenType(ScreenType screenType);
    public void removeScreenType(ScreenType screenType);

}