/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component onHoverType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface OnHoverType extends NiftyComponent {

    // attribute property change event names
    public static final String HOVERFALLOFFTYPE_PROPERTY = "hoverFalloffType"; // NOI18N
    public static final String HOVERFALLOFFCONSTRAINT_PROPERTY = "hoverFalloffConstraint"; // NOI18N
    public static final String HOVERWIDTH_PROPERTY = "hoverWidth"; // NOI18N
    public static final String HOVERHEIGHT_PROPERTY = "hoverHeight"; // NOI18N
    // child element property change event names

    public String getHoverFalloffType();
    public void setHoverFalloffType(String hoverFalloffType);
	
    public String getHoverFalloffConstraint();
    public void setHoverFalloffConstraint(String hoverFalloffConstraint);
	
    public String getHoverWidth();
    public void setHoverWidth(String hoverWidth);
	
    public String getHoverHeight();
    public void setHoverHeight(String hoverHeight);
	
}