/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component panelType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface PanelType extends NiftyComponent {

    // attribute property change event names
    // child element property change event names
    public static final String ELEMENTTYPE_PROPERTY = "elementType"; // NOI18N

    public List<ElementType> getElementTypes();
    public void addElementType(ElementType elementType);
    public void removeElementType(ElementType elementType);

}