/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import org.netbeans.modules.xml.xam.NamedReferenceable;
import org.netbeans.modules.xml.xam.Nameable;

/**
 * Interface for components in the Nifty domain that is referenceable.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface ReferenceableNiftyComponent
        extends NamedReferenceable<NiftyComponent>, Nameable<NiftyComponent>, NiftyComponent {
}