/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import org.netbeans.modules.xml.xam.Nameable;

/**
 * Interface for domain component registerEffectType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface RegisterEffectType extends NiftyComponent, Nameable<NiftyComponent> {

    // attribute property change event names
    public static final String CLASS_PROPERTY = "class"; // NOI18N
    // child element property change event names

    public String getEffectClass();
    public void setEffectClass(String _class);
	
}