/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component registerMouseCursorType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface RegisterMouseCursorType extends NiftyComponent {

    // attribute property change event names
    public static final String ID_PROPERTY = "id"; // NOI18N
    public static final String FILENAME_PROPERTY = "filename"; // NOI18N
    public static final String HOTSPOTX_PROPERTY = "hotspotX"; // NOI18N
    public static final String HOTSPOTY_PROPERTY = "hotspotY"; // NOI18N
    // child element property change event names

    public String getId();
    public void setId(String id);
	
    public String getFilename();
    public void setFilename(String filename);
	
    public String getHotspotX();
    public void setHotspotX(String hotspotX);
	
    public String getHotspotY();
    public void setHotspotY(String hotspotY);
	
}