/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component screenType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface ScreenType extends NiftyComponent {

    // attribute property change event names
    public static final String ID_PROPERTY = "id"; // NOI18N
    public static final String CONTROLLER_PROPERTY = "controller"; // NOI18N
    public static final String INPUTMAPPING_PROPERTY = "inputMapping"; // NOI18N
    public static final String DEFAULTFOCUSELEMENT_PROPERTY = "defaultFocusElement"; // NOI18N
    // child element property change event names
    public static final String LAYERTYPE_PROPERTY = "layerType"; // NOI18N

    public String getId();
    public void setId(String id);
	
    public String getController();
    public void setController(String controller);
	
    public String getInputMapping();
    public void setInputMapping(String inputMapping);
	
    public String getDefaultFocusElement();
    public void setDefaultFocusElement(String defaultFocusElement);
	
    public List<LayerType> getLayerTypes();
    public void addLayerType(LayerType layerType);
    public void removeLayerType(LayerType layerType);

}