/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component singleEffectType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface SingleEffectType extends NiftyComponent, SingleEffectTypeBase {

    // attribute property change event names
    // child element property change event names

}