/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;
import org.netbeans.modules.xml.xam.Nameable;

/**
 * Interface for domain component singleEffectTypeBase.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface SingleEffectTypeBase extends NiftyComponent, Nameable<NiftyComponent> {

    // attribute property change event names
    public static final String STARTDELAY_PROPERTY = "startDelay"; // NOI18N
    public static final String LENGTH_PROPERTY = "length"; // NOI18N
    public static final String ONESHOT_PROPERTY = "oneShot"; // NOI18N
    public static final String TIMETYPE_PROPERTY = "timeType"; // NOI18N
    public static final String FACTOR_PROPERTY = "factor"; // NOI18N
    public static final String INHERIT_PROPERTY = "inherit"; // NOI18N
    public static final String POST_PROPERTY = "post"; // NOI18N
    public static final String ALTERNATEENABLE_PROPERTY = "alternateEnable"; // NOI18N
    public static final String ALTERNATEDISABLE_PROPERTY = "alternateDisable"; // NOI18N
    public static final String ONSTARTEFFECT_PROPERTY = "onStartEffect"; // NOI18N
    public static final String ONENDEFFECT_PROPERTY = "onEndEffect"; // NOI18N
    // child element property change event names
    public static final String EFFECTVALUETYPE_PROPERTY = "effectValueType"; // NOI18N

    public String getStartDelay();
    public void setStartDelay(String startDelay);
	
    public String getLength();
    public void setLength(String length);
	
    public boolean isOneShot();
    public void setOneShot(boolean oneShot);
	
    public String getTimeType();
    public void setTimeType(String timeType);
	
    public String getFactor();
    public void setFactor(String factor);
	
    public boolean isInherit();
    public void setInherit(boolean inherit);
	
    public boolean isPost();
    public void setPost(boolean post);
	
    public String getAlternateEnable();
    public void setAlternateEnable(String alternateEnable);
	
    public String getAlternateDisable();
    public void setAlternateDisable(String alternateDisable);
	
    public String getOnStartEffect();
    public void setOnStartEffect(String onStartEffect);
	
    public String getOnEndEffect();
    public void setOnEndEffect(String onEndEffect);
	
    public List<EffectValueType> getEffectValueTypes();
    public void addEffectValueType(EffectValueType effectValueType);
    public void removeEffectValueType(EffectValueType effectValueType);

}