/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

import java.util.List;

/**
 * Interface for domain component singleEffectTypeOnHover.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface SingleEffectTypeOnHover extends NiftyComponent, SingleEffectType {

    // attribute property change event names
    // child element property change event names
    public static final String ONHOVERTYPE_PROPERTY = "onHoverType"; // NOI18N

    public List<OnHoverType> getOnHoverTypes();
    public void addOnHoverType(OnHoverType onHoverType);
    public void removeOnHoverType(OnHoverType onHoverType);

}