/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component singleEffectTypeHover.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface SingleEffectTypeHover extends NiftyComponent {

    // attribute property change event names
    public static final String WIDTH_PROPERTY = "width"; // NOI18N
    public static final String HEIGHT_PROPERTY = "height"; // NOI18N
    // child element property change event names

    public String getWidth();
    public void setWidth(String width);
	
    public String getHeight();
    public void setHeight(String height);
	
}