/*
 
 */
package com.jme3.gde.gui.extra.xam.model;


/**
 * Interface for domain component useStylesType.
 *
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public interface UseStylesType extends NiftyComponent {

    // attribute property change event names
    public static final String FILENAME_PROPERTY = "filename"; // NOI18N
    // child element property change event names

    public String getFilename();
    public void setFilename(String filename);
	
}