/*
 
 */
package com.jme3.gde.gui.extra.xam.model;

/**
 * An enum type in the Nifty domain.
 * 
 * @author cuongnguyen
 */
// Generated by XAM AutoGen Tool v0.2
public enum ValignType {
    TOP("top"),   // NOI18N
    CENTER("center"),   // NOI18N
    BOTTOM("bottom"),   // NOI18N
    ;

    private ValignType(String value) {
        this.value = value;
    }
    
    public String getValue() {
        return value;
    }
    
    public static ValignType getValignType(String value) {
        if (value == null) {
            return null;
        } else if ("top".equals(value)) {   // NOI18N
            return TOP;
        } else if ("center".equals(value)) {   // NOI18N
            return CENTER;
        } else if ("bottom".equals(value)) {   // NOI18N
            return BOTTOM;
        } else {
            assert false : "Invalid choice: " + value; 
            return null;
        }
    }
    
    private final String value;
}
